---
- name: Install nginx
  hosts: all
  become: true
  tasks:
  - name: Update all packages
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  - name: Install nginx
    apt:
      name: nginx
      state: latest

  - name: Enable nginx
    systemd:
      name: nginx
      state: restarted
      enabled: yes